### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by akabab** [akabab/lbc-watcher#2]
- [x] move telegram token to config
- [x] refactor config
- [x] add random seconds to delay
- [x] send formatted message to telegram
- [ ] handle offers.json file not exists error
- [ ] host to heroku
- [x] keep browser launched
- [ ] add telegram / commands
